version: "2.1"

services:
  # wifi-connect
  wifi-connect:
    build: ./wifi-connect
    restart: always
    network_mode: "host"
    privileged: true
    labels:
      io.balena.features.dbus: "1"
      io.balena.features.firmware: "1"
    cap_add:
      - NET_ADMIN
    environment:
      DBUS_SYSTEM_BUS_ADDRESS: "unix:path=/host/run/dbus/system_bus_socket"

  # hello-world-starter
  balena-hello-world:
    build: ./balena-nodejs-hello-world
    restart: always
    ports:
      - 3000:80
